//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdalnaSzkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class czlowiekSet_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public czlowiekSet_student()
        {
            this.OcenaStudentaSet = new HashSet<OcenaStudentaSet>();
        }
    
        public short RokStudiow { get; set; }
        public short NrAlbumu { get; set; }
        public int Id { get; set; }
    
        public virtual czlowiekSet czlowiekSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenaStudentaSet> OcenaStudentaSet { get; set; }
    }
}
