//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdalnaSzkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class czlowiekSet
    {
        public int Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public short Wiek { get; set; }
    
        public virtual czlowiekSet_nauczyciel czlowiekSet_nauczyciel { get; set; }
        public virtual czlowiekSet_student czlowiekSet_student { get; set; }
    }
}
