//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdalnaSzkola
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelSzkolyContainer : DbContext
    {
        public ModelSzkolyContainer()
            : base("name=ModelSzkolyContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<czlowiekSet> czlowiekSet { get; set; }
        public virtual DbSet<czlowiekSet_nauczyciel> czlowiekSet_nauczyciel { get; set; }
        public virtual DbSet<czlowiekSet_student> czlowiekSet_student { get; set; }
        public virtual DbSet<OcenaStudentaSet> OcenaStudentaSet { get; set; }
        public virtual DbSet<PrzedmiotSet> PrzedmiotSet { get; set; }
    }
}
