//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdalnaSzkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcenaStudentaSet
    {
        public int Id { get; set; }
        public decimal Ocena { get; set; }
        public System.DateTime DataWstawienia { get; set; }
        public short Semestr { get; set; }
        public short Termin { get; set; }
        public int student_Id { get; set; }
        public int Przedmiot_Id { get; set; }
        public int nauczyciel_Id { get; set; }
    
        public virtual czlowiekSet_nauczyciel czlowiekSet_nauczyciel { get; set; }
        public virtual czlowiekSet_student czlowiekSet_student { get; set; }
        public virtual PrzedmiotSet PrzedmiotSet { get; set; }
    }
}
